### ISSUE TITLE
bug:程序第一次调用成功进入微信支付界面，退回后再次发起就再也进不去了，发送无任何反应，进入不了微信支付界面

### ISSUE THREAD

**Issue by yyy522426** [mayubao/Android-Pay#24]
第一次调用能成功跳转到支付界面，退回再次发起无任何反应，不是回调的问题，是压根就没跳转到支付界面，通过断点测试，程序到达 mWXApi.sendReq(request)停止，微信的onResp（）方法没有进入，初步推测请求不成功，但是sendReq（request）请求不成功不是应该有不成功的返回值吗？界面不跳转，却莫名的弹出软键盘，做测试的为正式商业用并已签名的APPID,，测试Android机32G+4G Android7.0真机，微信为最新版本。

**Comment by mayubao** [comment]
保证在微信后台申请的应用签名是一致~ @yyy522426
