### ISSUE TITLE
微信支付是否可以多个商户

### ISSUE THREAD

**Issue by BinarySatan** [mayubao/Android-Pay#4]
微信支付是否可以指定 多个商户,  如 一个包名对应 多个key。     微信根据key的不同, 钱流到不同的账户上面?  支持吗

**Comment by mayubao** [comment]
这个key指的是什么key？ @BinarySatan

**Comment by BinarySatan** [comment]
@mayubao  就是微信的唯一标识。    目前想实现的是,   在客户端传给微信不同的 标识,  好让微信知道 钱最终的走向。  不知道可行不可行。

**Comment by mayubao** [comment]
这个没试过

**Comment by star-andy** [comment]
应该可以的  我的登录和支付走的就不是一个key
只要在app里面注册微信的api时注册你要支付的商户应该就可以

**Comment by BinarySatan** [comment]
@qinyang1018 就是说 一个包名 可以申请多个key,  都可以用对吧。

**Comment by star-andy** [comment]
恩  可以

**Comment by BinarySatan** [comment]
@qinyang1018 好的，谢谢。
